---
- hosts: all
  become: yes
  vars:
    ros2_distribution: humble
    # Default username and group for catkin_ws installation
    # https://moveit.ai/install-moveit2/source/
    ros2_packages:
      - foxglove-bridge
      - generate-parameter-library
      - turtlesim
      - ros-gz
      - gazebo-ros-pkgs
      - ros-ign-bridge
      - gazebo-plugins
      - navigation2
      - py-trees-ros
      - py-trees-ros-viewer
      #- speech-recognition
      #- text-to-speech

    ros2_user:
        name: vagrant
        group: vagrant
    
    packages:
      - ros-dev-tools
      - python3-pip
      - python3-venv
      - python3-colcon-common-extensions
      - python3-colcon-mixin
      - python3-flake8
      - python3-rosdep
      - python3-setuptools
      - python3-vcstool
      - build-essential
      - cmake
      - git
      - wget
      - tree
      - vim
      # https://stackabuse.com/managing-python-environments-with-direnv-and-pyenv/
      - direnv
      - screen
      - htop

    de_packages:
      - thunderbird-locale-de
      - thunderbird-locale-en
      - thunderbird-locale-en-gb
      - thunderbird-locale-en-us
      - mythes-de
      - mythes-de-ch
      - mythes-en-au
      - libreoffice-help-de
      - libreoffice-l10n-en-za
      - libreoffice-l10n-en-gb
      - libreoffice-l10n-de
      - hunspell-de-ch-frami
      - hunspell-de-de-frami
      - hunspell-de-at-frami
      - gnome-user-docs-de
      - hyphen-en-ca
      - hyphen-en-gb
      - hyphen-de
      - libreoffice-help-en-gb
      - chromium-browser-l10n

    pip_install_packages:
      - name: docker

    docker_users:
      - vagrant
    
  roles:
    - rarrais.ros2
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Read-write git checkout from github
      become_user: vagrant
      ansible.builtin.git:
        repo: "{{item.repo}}"
        dest: "{{item.dest}}"
        version: "{{item.version}}"
        update: no
      loop:
        - repo: https://github.com/DUDULRX/waveshare_roarm_sdk.git
          dest: /home/vagrant/waveshare_roarm_sdk
          version: "main"
        - repo: https://github.com/DUDULRX/roarm_ws.git
          dest: /home/vagrant/roarm_ws
          version: "ros2-humble"
        - repo: https://github.com/pib-rocks/pib-backend
          dest: /home/vagrant/pib-backend
          version: "main"
        - repo: https://github.com/wentasah/ros-direnv.git
          dest: /home/vagrant/ros-direnv
          version: "main"
        - repo: https://github.com/mmmarinho/ROS2_Tutorial.git
          dest: /home/vagrant/ROS2_Tutorial
          version: "main"
        - repo: https://github.com/EduArt-Robotik/edu_simulation.git
          dest: /home/vagrant/eduart-simulator/src/edu_simulation
          version: "main"
        - repo: https://github.com/EduArt-Robotik/edu_robot.git
          dest: /home/vagrant/eduart-simulator/src/edu_robot
          version: "develop"
    
    - name: Build edu_robot and edu_simulation
      become_user: vagrant
      become_method: su 
      become_flags: --login
      ansible.builtin.shell: |
        source /home/vagrant/.bashrc
        
        # Set the ROS distribution environment variable
        export ROS_DISTRO=${ROS_DISTRO:={{ros2_distribution}}}
        
        # Set the ROS Python version (default is 3)
        export ROS_PYTHON_VERSION=${ROS_PYTHON_VERSION:=3}

        # Set the ROS version (default is 2)
        export ROS_VERSION=${ROS_VERSION:=2}

        # Source the ROS setup file for the specified distribution
        source /opt/ros/${ROS_DISTRO}/setup.bash

        # Update the PATH environment variable to include ROS-related directories
        export PATH=/opt/ros/${ROS_DISTRO}/opt/gz_tools_vendor/bin:/opt/ros/${ROS_DISTRO}/bin:/home/vagrant/google-cloud-sdk/bin:/home/vagrant/.rbenv/shims:/home/vagrant/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
        
        # Set the COLCON workspace directory
        export COLCON_WS= 
        echo $ROS_DISTRO as $USER

        cd ${COLCON_WS}
        colcon build --packages-select {{item}} --event-handlers console_direct+ --symlink-install
      args:
        executable: /usr/bin/bash
        chdir: /home/vagrant/eduart-simulator
      loop:
        - edu_robot
        - edu_simulation
      changed_when: false
      register: colcon_build

    - ansible.builtin.debug:
        var: colcon_build

    - name: Prepare .bashrc for pycharm and autocompletion
      ansible.builtin.lineinfile:
        path: /home/vagrant/.bashrc
        line: "{{item.line}}"
        regexp: '{{item.regexp}}'
        insertafter: "{{item.insertafter | default('EOF')}}"
        state: "{{item.state | default('present')}}"
      loop:
        # Todo remove if in Version
        - line: /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash
          regexp: ^/usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash
          state: absent
        # Todo remove if in Version
        - line: alias pycharm_ros2=~/ros2_workspace_pycharm/pycharm-community-2023.1.1/bin/pycharm.sh
          regexp: ^alias pycharm_ros2=~/ros2_workspace_pycharm/pycharm-community-2023.1.1/bin/pycharm.sh
          state: absent
        # Remain setup
        - line: '# Alias for PyCharm, as instructed in https://ros2-tutorial.readthedocs.io'
          regexp: ^# Alias for PyCharm, as instructed in https://ros2-tutorial.readthedocs.io
        - line: alias pycharm_ros2=~/ros2_workspace_pycharm/pycharm-community-2023.1.1/bin/pycharm.sh
          regexp: ^alias pycharm_ros2=~/ros2_workspace_pycharm/pycharm-community-2023.1.1/bin/pycharm.sh
          insertafter: '^# Alias for PyCharm, as instructed in https://ros2-tutorial.readthedocs.io'
        - line: '# For autocompletion colcon'
          regexp: ^# For autocompletion colcon
        - line: source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash
          regexp: ^source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash
          insertafter: ^# For autocompletion colcon
    
    - name: Removes old workspace
      ansible.builtin.file:
        path: "/home/vagrant/pycharm-community-2023.1.1"
        state: absent

    - name: Creates pycharm workspace
      ansible.builtin.file:
        path: "/home/vagrant/{{item}}"
        state: directory
      loop:
        - eduart-simulator/src
        - ros2_workspace_pycharm

    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: "{{item.src}}"
        dest: "{{item.dest | default('/home/vagrant/')}}"
        owner: vagrant
        group: vagrant
        remote_src: yes
        creates: "{{item.dest | default('/home/vagrant/')}}{{item.path}}"
      loop:
        - src: https://files.waveshare.com/wiki/RoArm-M2-S/Roarm_ws_em0.zip
          path: "roarm_ws_em0"
        - src: https://files.waveshare.com/wiki/RoArm-M2-S/Roarm_ws_em1.zip
          path: "roarm_ws_em1"
        - src: https://download.jetbrains.com/python/pycharm-community-2023.1.1.tar.gz
          path: "pycharm-community-2023.1.1"
          dest: "/home/vagrant/ros2_workspace_pycharm/"
    
    - name: Wayland deactivate
      lineinfile:
        path: "{{item.path}}"
        line: "{{item.line}}"
        regexp: "{{item.regexp}}"
      loop:
        - path: /etc/gdm3/custom.conf 
          line: WaylandEnable=false
          regexp: ^#WaylandEnable=false
        - path: /etc/ssh/sshd_config
          line: X11Forwarding yes
          regexp: ^#X11Forwarding

    # https://moveit.ai/install-moveit2/source/
    # https://moveit.ai/install-moveit2/source/#uninstall-any-pre-existing-moveit-debians
    - name: Install packeges beginner tutorial with apt-get because ansible apt support no regex
      ansible.builtin.command: apt-get remove --yes ~nros-humble-moveit*
      changed_when: false

    - name: Install packeges
      ansible.builtin.apt:
        name: "{{item}}"
        cache_valid_time: 3600
        update_cache: yes
      loop: "{{packages}}"
    
    # This script sets up a ROS environment, removes unnecessary packages, initializes rosdep, 
    # clones a MoveIt2 tutorial repository, adds a default mixin repository, installs dependencies,
    # and builds the project using colcon.
    # https://moveit.picknik.ai/humble/doc/tutorials/tutorials.html
    # https://aleksandarhaber.com/how-to-move-robot-using-moveit-2-in-rviz-and-ros2-and-how-to-perform-motion-planning/
    - name: Install Moveit Tutorial
      become_user: vagrant
      become_method: su 
      become_flags: --login
      ansible.builtin.shell: |
        source /home/vagrant/.bashrc
        
        # Set the ROS distribution environment variable
        export ROS_DISTRO=${ROS_DISTRO:={{ros2_distribution}}}
        
        # Set the ROS Python version (default is 3)
        export ROS_PYTHON_VERSION=${ROS_PYTHON_VERSION:=3}

        # Set the ROS version (default is 2)
        export ROS_VERSION=${ROS_VERSION:=2}

        # Source the ROS setup file for the specified distribution
        source /opt/ros/${ROS_DISTRO}/setup.bash

        # Update the PATH environment variable to include ROS-related directories
        export PATH=/opt/ros/${ROS_DISTRO}/opt/gz_tools_vendor/bin:/opt/ros/${ROS_DISTRO}/bin:/home/vagrant/google-cloud-sdk/bin:/home/vagrant/.rbenv/shims:/home/vagrant/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
        
        # Set the COLCON workspace directory
        export COLCON_WS=/home/vagrant/ws_moveit2/
        echo $ROS_DISTRO as $USER

        # Remove ROS MoveIt packages
        # sudo apt remove ros-$ROS_DISTRO-moveit*

        # Clean up unused dependencies
        sudo apt autoremove

        # Update package lists and upgrade installed packages
        sudo apt update
        sudo apt dist-upgrade --yes

        # Initialize rosdep if it doesn't exist
        if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]
        then
          sudo rosdep init
        fi

        # Update rosdep sources
        rosdep update || true

        # rm -rf $COLCON_WS

        # Create the src directory if it doesn't exist
        if [ ! -d $COLCON_WS/src ]
        then
          mkdir -p $COLCON_WS/src
          cd $COLCON_WS/src
          # Clone the MoveIt2 tutorials repository
          git clone -b ${ROS_DISTRO} https://github.com/moveit/moveit2_tutorials
        else
          cd $COLCON_WS/src
        fi

        # Add default mixin repository and update the default mixin repository
        colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
        colcon mixin update default

        # Import MoveIt2 tutorials repository recursively
        vcs import --recursive < moveit2_tutorials/moveit2_tutorials.repos

        # Update package lists
        sudo apt update

        # Install dependencies for the project
        rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y

        # Build the project using colcon
        colcon build --executor sequential --mixin release
      args:
        executable: /usr/bin/bash
      changed_when: false
      register: colcon_build

    - ansible.builtin.debug:
        var: colcon_build


    #- name: Install Python dependencies
    #  ansible.builtin.pip:
    #    requirements: /home/vagrant/waveshare_roarm_sdk/requirements.txt

    #- name: Install waveshare roarm sdk
    #  ansible.builtin.command:
    #    cmd: python3 setup.py install
    #    chdir: /home/vagrant/waveshare_roarm_sdk
    #  changed_when: false

    # sudo apt install '~nros-humble-rqt*' Packages to install for turtle tutorial
    # https://docs.ros.org/en/jazzy/Tutorials/Beginner-CLI-Tools/Introducing-Turtlesim/Introducing-Turtlesim.html#install-rqt
    - name: Install packeges beginner tutorial with apt-get because ansible apt support no regex
      ansible.builtin.command: apt-get install --yes ~nros-humble-rqt*
      changed_when: false

    
    # sudo snapp install code --classic
    - name: Install code via snap
      community.general.snap:
        classic: yes
        name: code

    - name: Ensure a locale exists
      community.general.locale_gen:
        name: de_DE.UTF-8
        state: present

    - name: Ensure de is set
      ansible.builtin.lineinfile:
        regexp: XKBLAYOUT="gb"
        line: XKBLAYOUT="de"
        path: /etc/default/keyboard
        
    
    # Install locale for desktop packeges
    - name: Install de packeges
      ansible.builtin.apt:
        name: "{{item}}"
        cache_valid_time: 3600
        update_cache: yes
      loop: "{{de_packages}}"

    # GUI Loss Problem
    # https://www.waveshare.com/wiki/RoArm-M2-S_ROS2_Getting_Started_Tutorial#GUI_Loss_Problem
    - name: Install tasksel
      ansible.builtin.apt:
        name: tasksel
        cache_valid_time: 3600
        update_cache: yes

    - name: Install Ubuntu Desktop via tasksel
      ansible.builtin.command: tasksel install ubuntu-desktop
      changed_when: false

    - name: Install ubuntu-desktop
      ansible.builtin.apt:
        name:
          - ubuntu-desktop
        cache_valid_time: 3600
        update_cache: yes

    - name: Set owner of /home/vagrant. Failed because snap is read-only.
      become: yes
      ansible.builtin.file:
        path: /home/vagrant
        owner: vagrant
        group: vagrant
        recurse: yes
      failed_when: false



