---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: geerlingguy.nfs

    # Not working 
    #- role: geerlingguy.packer-debian
    #  when: ansible_os_family == 'Debian'

  pre_tasks:
    # Taken from geerlingguy.packer
    - name: Ensure apt cache is updated.
      apt: update_cache=yes cache_valid_time=3600

    # SSH daemon configuration.
    - name: Configure SSH daemon.
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: '^UseDNS'
          line: 'UseDNS no'
        - regexp: '^GSSAPIAuthentication'
          line: 'GSSAPIAuthentication no'

    # Vagrant SSH configuration.
    - name: Configure Vagrant .ssh directory.
      file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0700

    - name: Get Vagrant's public key.
      get_url:
        url: https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub
        dest: /home/vagrant/.ssh/authorized_keys
        owner: vagrant
        group: vagrant
        mode: 0600

    # Cleanup tasks.
    - name: Remove unneeded packages.
      apt:
        name:
          - ppp
          - pppconfig
          - pppoeconf
          - cpp
          - gcc
          - g++
          - libx11-data
          - xauth
          - libxmuu1
          - libxcb1
          - libx11-6
          - libxext6
          - linux-source
        state: absent

  tasks:
    - name: Install some helpful utilities.
      apt:
        name:
          - git
          - wget
          - curl
          - vim
          - jq
        state: present
      when: ansible_os_family == 'Debian'

    - name: Disable Suspend And Hibernation In Linux
      command: systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target
